# -*- coding: utf-8 -*-
"""Xiang_Yichen_pset4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14INJeta2PYeIgCri6ffBxVa2TP6xiecG
"""

import pandas as pd
import matplotlib.pyplot as plt


crabn=pd.read_csv('/content/Uploaded Feature List_CrabUrine_neg_V2.txt',sep='\t')

known_n=crabn.dropna(subset=["Formula"])

known = known_n.loc[known_n['Name'].str.contains("_")]

Name_chemicals=known_n.drop(known.index)

crab_chemical=Name_chemicals.dropna( axis=1)

neg_list= crab_chemical.groupby('Name')['MA',"MB","MD","OA","OC","OD"].transform('sum')

new_list=neg_list.sort_values(by="MA",ascending=False).drop_duplicates()

final_n=crab_chemical.loc[new_list.index].sort_values(by="MA",ascending=False)

import numpy as np
import matplotlib.pyplot as plt
X = np.arange(10)
final_n.reset_index

fig = plt.figure()
ax = fig.add_axes([0,0,1,1])
ploty=[]
ploty=pd.DataFrame(ploty)
ploty[0]=final_n['MA']
ploty[1]=final_n['MB']
ploty[2]=final_n['MD']
ploty[3]=final_n['OA']
ploty[4]=final_n['OC']
ploty[5]=final_n['OD']
ploty[6]=final_n['Name']
for i in range(6):
  ax.bar(X + 0.1*i, ploty[i][0:10], color=(0.15*i, 0, 0.1, 0.9), width = 0.1,label=final_n.columns[i+8])
  ax.legend()
ax.set_xticks([0,1,2,3,4,5,6,7,8,9])
ax.set_yscale('log')
ax.set_xticklabels(ploty[6][0:10],rotation=90)
ax.set_ylabel("MS Peak")
plt.title("Top 10 Chemicals Found in Crab Urine")

plt.show()